server:
  port: 9090
  tomcat:
    basedir: C:/temp
    accesslog:
      enabled: false
    uri-encoding: UTF-8
    max-http-header-size: 8192

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hrmplatform00@gmail.com
    password: yuiw pcml vlqc jpsq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: hrmplatform
      password: Hrm12345
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${HRM_POSTGRE_URL}
    username: ${HRM_POSTGRE_USERNAME}
    password: ${HRM_POSTGRE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

hrmplatform:
  jwt:
    secret-key: ${HRM_JWT_SECRETKEY}
    issuer: ${HRM_JWT_ISSUER}
  siteAdminEmail: hrmplatform00@gmail.com

app:
  base-url: http://localhost:9090